# Form implementation generated from reading ui file 'Bai_96_Ui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 577)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_1 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(210, 70, 311, 231))
        self.groupBox_1.setObjectName("groupBox_1")
        self.label = QtWidgets.QLabel(parent=self.groupBox_1)
        self.label.setGeometry(QtCore.QRect(40, 30, 55, 16))
        self.label.setObjectName("label")
        self.name = QtWidgets.QLineEdit(parent=self.groupBox_1)
        self.name.setGeometry(QtCore.QRect(130, 30, 113, 22))
        self.name.setObjectName("name")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_1)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 55, 16))
        self.label_2.setObjectName("label_2")
        self.Rb_gender = QtWidgets.QRadioButton(parent=self.groupBox_1)
        self.Rb_gender.setGeometry(QtCore.QRect(140, 80, 95, 20))
        self.Rb_gender.setObjectName("Rb_gender")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_1)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 55, 16))
        self.label_3.setObjectName("label_3")
        self.comb_city = QtWidgets.QComboBox(parent=self.groupBox_1)
        self.comb_city.setGeometry(QtCore.QRect(140, 140, 111, 22))
        self.comb_city.setObjectName("comb_city")
        self.pB_conf = QtWidgets.QPushButton(parent=self.groupBox_1)
        self.pB_conf.setGeometry(QtCore.QRect(90, 180, 93, 28))
        self.pB_conf.setObjectName("pB_conf")
        self.pB_close = QtWidgets.QPushButton(parent=self.groupBox_1)
        self.pB_close.setGeometry(QtCore.QRect(200, 180, 93, 28))
        self.pB_close.setObjectName("pB_close")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 330, 321, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.textEdit.setGeometry(QtCore.QRect(60, 30, 211, 87))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_1.setTitle(_translate("MainWindow", "Input Information "))
        self.label.setText(_translate("MainWindow", "Full name"))
        self.label_2.setText(_translate("MainWindow", "Gender"))
        self.Rb_gender.setText(_translate("MainWindow", "Woman"))
        self.label_3.setText(_translate("MainWindow", "City"))
        self.pB_conf.setText(_translate("MainWindow", "Confirm "))
        self.pB_close.setText(_translate("MainWindow", "Close"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output Ìnormation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
